AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  roboclipper_match_uploader

  Sample SAM Template for roboclipper_match_uploader

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 3008
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  RoboclipperMatchUploaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "RoboclipperMatchUploader"
      Description: "An automated YouTube uploader responding on cut files from an SNS topic"
      CodeUri: roboclipper_match_uploader/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Environment:
        Variables:
          EVENT_NAME: "WA - Asimov"
          EVENT_TYPE: "Semifinal"
          EVENT_DESCRIPTION: "Event Information: \n
                              FIRST Washington - https://firstwa.org/ \n
                              Official FIRST Data Source - https://ftc-events.firstinspires.org/2024/region/USWA"
          EVENT_PLAYLIST: "PLoRnKfyWNUleDroiOiFaxPXGPPqZJ8Fvr"
          SEASON_NAME: "Into The Deep"
      Events:
        RoboclipperSNSReceived:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-west-2:267253737119:RobotClipperStack-FinalBucketObjectCreate95F1ECF1-TdiDydFsHLan

Outputs:
  RoboclipperMatchUploaderFunction:
    Description: Roboclipper Match Uploader Lambda Function ARN
    Value: !GetAtt RoboclipperMatchUploaderFunction.Arn